name: Generate Pacmanon:schedule:- cron: "0 */6 * * *" # jalan tiap 6 jamworkflow_dispatch:permissions:contents: writecegah dua job saling tabrak commitconcurrency:group: pacmancancel-in-progress: truejobs:build:runs-on: ubuntu-lateststeps:- name: Checkoutuses: actions/checkout@v4  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: "20"

  - name: Prepare dirs
    run: |
      set -euo pipefail
      mkdir -p dist output

  # === Generator pacman (pakai CLI npm) ===
  - name: Run pacman generator
    run: |
      #!/bin/bash
      set -euo pipefail
      # Jalankan generator. Perbaikan: Mengganti paket yang tidak ditemukan
      # 'github-profile-pacman' menjadi 'pacman-contribution-graph'
      npx --yes pacman-contribution-graph --user Abelion512 --out dist

      # Normalisasi nama file agar sesuai dengan yang dibaca README
      # Banyak generator menulis nama yang berbeda, jadi kita pastikan konsisten.
      DARK_CANDIDATE="$(ls dist | grep -Ei 'dark.*\.svg$' || true)"
      LIGHT_CANDIDATE="$(ls dist | grep -Ei '(^|[^-])pacman.*\.svg$' || true)"

      # Jika tidak ketemu, fallback: anggap ada pacman.svg dan pacman-dark.svg
      if [ -z "$LIGHT_CANDIDATE" ] && [ -f dist/pacman.svg ]; then LIGHT_CANDIDATE="pacman.svg"; fi
      if [ -z "$DARK_CANDIDATE" ] && [ -f dist/pacman-dark.svg ]; then DARK_CANDIDATE="pacman-dark.svg"; fi

      # Validasi minimal satu file ada
      test -n "$LIGHT_CANDIDATE" || { echo "Pacman light SVG tidak ditemukan"; exit 1; }

      # Jika dark tidak tersedia, pakai light sebagai fallback
      if [ -z "$DARK_CANDIDATE" ]; then
        cp "dist/$LIGHT_CANDIDATE" dist/pacman-contribution-graph-dark.svg
      else
        cp "dist/$DARK_CANDIDATE" dist/pacman-contribution-graph-dark.svg
      fi

      cp "dist/$LIGHT_CANDIDATE" dist/pacman-contribution-graph.svg

      # Pastikan dua file final ada dan berisi
      test -s dist/pacman-contribution-graph.svg
      test -s dist/pacman-contribution-graph-dark.svg

  - name: Publish to output/
    run: |
      set -euo pipefail
      cp dist/pacman-contribution-graph*.svg output/
      git config user.name  "github-actions[bot]"
      git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      git add output/pacman-contribution-graph*.svg
      git commit -m "chore: update pacman graph" || echo "no changes"
      git push
