# .github/workflows/pacman.yml
name: Generate Pacman

on:
  schedule:
    - cron: "30 1 * * *"   # 1x sehari
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # GANTI STEP INI sesuai generator pacman yang kamu pakai
      - name: Run pacman generator
        run: |
          ./scripts/generate-pacman.sh  # atau node scripts/generate-pacman.mjs
          # pastikan script menulis ke: output/pacman-contribution-graph.svg
          # dan output/pacman-contribution-graph-dark.svg

      - name: Commit updated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/pacman-contribution-graph*.svg
          git commit -m "chore: update pacman graph" || echo "no changes"
          git push
